# Jokes-ui service load balancer
kind: Service
apiVersion: v1
metadata:
  name: alumni-ui
spec:
  type: LoadBalancer
 # type: ClusterIP
  ports:
    - port: 4000
      targetPort: 80
      protocol: TCP
  selector:
    app: alumni-ui